export const INITIAL_SICK_LEAVES = [
  {
    id: 'SL-001',
    workerName: 'Alejandro Ramos',
    workerEmail: 'alejandro.ramos@alphatech.com',
    workerMobile: '+34 612 345 678',
    workerSex: 'Male',
    company: 'AlphaTech Solutions',
    department: 'Engineering',
    workCenter: 'Headquarters (Main)',
    startDate: '2026-01-10',
    endDate: '2026-01-24',
    pathology: 'Musculoskeletal',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Severe lower back pain due to herniated disc. Required physical therapy.',
  },
  {
    id: 'SL-002',
    workerName: 'Elena Gómez',
    workerEmail: 'elena.gomez@alphatech.com',
    workerMobile: '+34 623 456 789',
    workerSex: 'Female',
    company: 'AlphaTech Solutions',
    department: 'Engineering',
    workCenter: 'Headquarters (Main)',
    startDate: '2026-05-15',
    endDate: null,
    pathology: 'Mental Health',
    leaveType: 'Common Illness',
    status: 'Active',
    notes: 'Anxiety and burnout clinical diagnosis. Prescribed strict rest.',
  },
  {
    id: 'SL-003',
    workerName: 'David Vance',
    workerEmail: 'd.vance@globallogistics.com',
    workerMobile: '+1 555-0198',
    workerSex: 'Male',
    company: 'Global Logistics Corp',
    department: 'Operations',
    workCenter: 'North Logistics Center',
    startDate: '2025-10-05',
    endDate: '2025-10-12',
    pathology: 'Respiratory',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Influenza infection with high fever.',
  },
  {
    id: 'SL-004',
    workerName: 'Sarah Jenkins',
    workerEmail: 's.jenkins@globallogistics.com',
    workerMobile: '+1 555-0142',
    workerSex: 'Female',
    company: 'Global Logistics Corp',
    department: 'Operations',
    workCenter: 'North Logistics Center',
    startDate: '2026-03-01',
    endDate: '2026-03-25',
    pathology: 'Surgery Recovery',
    leaveType: 'Non-Occupational Accident',
    status: 'Completed',
    notes: 'Appendectomy surgery and subsequent domestic recovery.',
  },
  {
    id: 'SL-005',
    workerName: 'Carlos Santillana',
    workerEmail: 'carlos.s@apexretail.com',
    workerMobile: '+34 688 991 223',
    workerSex: 'Male',
    company: 'Apex Retail',
    department: 'Sales & Marketing',
    workCenter: 'East Coast Branch',
    startDate: '2026-04-12',
    endDate: '2026-04-18',
    pathology: 'Digestive',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Acute gastroenteritis. Food poisoning suspected.',
  },
  {
    id: 'SL-006',
    workerName: 'Marta Rivas',
    workerEmail: 'marta.rivas@apexretail.com',
    workerMobile: '+34 677 882 110',
    workerSex: 'Female',
    company: 'Apex Retail',
    department: 'Customer Support',
    workCenter: 'East Coast Branch',
    startDate: '2026-05-10',
    endDate: '2026-05-14',
    pathology: 'Respiratory',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Pharyngobronchitis with loss of voice.',
  },
  {
    id: 'SL-007',
    workerName: 'Jean-Pierre Laurent',
    workerEmail: 'jp.laurent@novahealth.com',
    workerMobile: '+33 6 1234 5678',
    workerSex: 'Male',
    company: 'Nova Health',
    department: 'Finance',
    workCenter: 'Headquarters (Main)',
    startDate: '2025-11-20',
    endDate: '2025-12-15',
    pathology: 'Cardiovascular',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Hypertensive crisis. Monitored for cardio-vascular risk adjustment.',
  },
  {
    id: 'SL-008',
    workerName: 'Sofia Lindstrom',
    workerEmail: 'sofia.l@horizon.com',
    workerMobile: '+46 8 123 45 67',
    workerSex: 'Female',
    company: 'Horizon Manufacturing',
    department: 'Operations',
    workCenter: 'South Factory',
    startDate: '2026-02-18',
    endDate: '2026-04-02',
    pathology: 'Musculoskeletal',
    leaveType: 'Occupational Accident',
    status: 'Completed',
    notes: 'Sprained ankle after slipping on the loading dock. Safety protocols reviewed.',
  },
  {
    id: 'SL-009',
    workerName: 'Sofia Lindstrom',
    workerEmail: 'sofia.l@horizon.com',
    workerMobile: '+46 8 123 45 67',
    workerSex: 'Female',
    company: 'Horizon Manufacturing',
    department: 'Operations',
    workCenter: 'South Factory',
    startDate: '2026-05-20',
    endDate: null,
    pathology: 'Musculoskeletal',
    leaveType: 'Occupational Disease',
    status: 'Active',
    notes: 'Carpal tunnel syndrome flare-up, ergonomic assessment scheduled.',
  },
  {
    id: 'SL-010',
    workerName: 'Jonathan Wu',
    workerEmail: 'j.wu@alphatech.com',
    workerMobile: '+1 555-0177',
    workerSex: 'Male',
    company: 'AlphaTech Solutions',
    department: 'Engineering',
    workCenter: 'West R&D Lab',
    startDate: '2026-05-02',
    endDate: '2026-05-12',
    pathology: 'Infectious Diseases',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Shingles outbreak, highly contagious phase.',
  },
  {
    id: 'SL-011',
    workerName: 'Isabella Rossi',
    workerEmail: 'i.rossi@novahealth.com',
    workerMobile: '+39 333 445 5667',
    workerSex: 'Female',
    company: 'Nova Health',
    department: 'Human Resources',
    workCenter: 'Headquarters (Main)',
    startDate: '2026-01-15',
    endDate: '2026-02-10',
    pathology: 'Mental Health',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Adjustment disorder. Accompanied by psychological counseling sessions.',
  },
  {
    id: 'SL-012',
    workerName: 'Lucas Dubois',
    workerEmail: 'l.dubois@globallogistics.com',
    workerMobile: '+33 7 8899 0011',
    workerSex: 'Male',
    company: 'Global Logistics Corp',
    department: 'Operations',
    workCenter: 'North Logistics Center',
    startDate: '2026-05-22',
    endDate: null,
    pathology: 'Other',
    leaveType: 'Non-Occupational Accident',
    status: 'Active',
    notes: 'Fractured wrist during weekend amateur cycling.',
  },
  {
    id: 'SL-013',
    workerName: 'Anna Kowalski',
    workerEmail: 'a.kowalski@horizon.com',
    workerMobile: '+48 601 234 567',
    workerSex: 'Female',
    company: 'Horizon Manufacturing',
    department: 'Operations',
    workCenter: 'South Factory',
    startDate: '2025-08-10',
    endDate: '2025-08-30',
    pathology: 'Surgery Recovery',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Knee arthroscopy to repair torn meniscus.',
  },
  {
    id: 'SL-014',
    workerName: 'Miguel Angel',
    workerEmail: 'miguel.angel@apexretail.com',
    workerMobile: '+34 600 112 233',
    workerSex: 'Male',
    company: 'Apex Retail',
    department: 'Sales & Marketing',
    workCenter: 'East Coast Branch',
    startDate: '2026-02-01',
    endDate: '2026-02-05',
    pathology: 'Respiratory',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Seasonal flu, bed rest recommended.',
  },
  {
    id: 'SL-015',
    workerName: 'Alejandro Ramos',
    workerEmail: 'alejandro.ramos@alphatech.com',
    workerMobile: '+34 612 345 678',
    workerSex: 'Male',
    company: 'AlphaTech Solutions',
    department: 'Engineering',
    workCenter: 'Headquarters (Main)',
    startDate: '2026-04-10',
    endDate: '2026-04-14',
    pathology: 'Digestive',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Severe colic. Resolved after 4 days of rest.',
  },
  {
    id: 'SL-016',
    workerName: 'Diana Prince',
    workerEmail: 'diana.p@novahealth.com',
    workerMobile: '+1 555-0100',
    workerSex: 'Female',
    company: 'Nova Health',
    department: 'Customer Support',
    workCenter: 'West R&D Lab',
    startDate: '2026-05-24',
    endDate: null,
    pathology: 'Respiratory',
    leaveType: 'Common Illness',
    status: 'Active',
    notes: 'COVID-19 positive, isolating at home with mild symptoms.',
  },
  {
    id: 'SL-017',
    workerName: 'Tom Cruise',
    workerEmail: 't.cruise@globallogistics.com',
    workerMobile: '+1 555-0112',
    workerSex: 'Male',
    company: 'Global Logistics Corp',
    department: 'Operations',
    workCenter: 'North Logistics Center',
    startDate: '2026-01-05',
    endDate: '2026-01-20',
    pathology: 'Other',
    leaveType: 'Occupational Accident',
    status: 'Completed',
    notes: 'Minor back strain during forklift operation. Received training refresh.',
  },
  {
    id: 'SL-018',
    workerName: 'Robert Downey',
    workerEmail: 'r.downey@alphatech.com',
    workerMobile: '+1 555-0155',
    workerSex: 'Male',
    company: 'AlphaTech Solutions',
    department: 'Engineering',
    workCenter: 'Headquarters (Main)',
    startDate: '2025-12-15',
    endDate: '2026-01-10',
    pathology: 'Surgery Recovery',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Gallbladder removal surgery.',
  },
  {
    id: 'SL-019',
    workerName: 'Scarlett Johansson',
    workerEmail: 's.johansson@apexretail.com',
    workerMobile: '+1 555-0188',
    workerSex: 'Female',
    company: 'Apex Retail',
    department: 'Finance',
    workCenter: 'East Coast Branch',
    startDate: '2026-03-12',
    endDate: '2026-03-22',
    pathology: 'Mental Health',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Severe stress episodes. Ergonomic check for posture and workspace noise.',
  },
  {
    id: 'SL-020',
    workerName: 'Arthur Dent',
    workerEmail: 'a.dent@horizon.com',
    workerMobile: '+44 7700 900077',
    workerSex: 'Male',
    company: 'Horizon Manufacturing',
    department: 'Finance',
    workCenter: 'South Factory',
    startDate: '2026-05-01',
    endDate: '2026-05-15',
    pathology: 'Digestive',
    leaveType: 'Common Illness',
    status: 'Completed',
    notes: 'Stomach ulcer treatment and follow-up diet adjustment.',
  }
];

export const AVAILABLE_COMPANIES = [
  'AlphaTech Solutions',
  'Global Logistics Corp',
  'Apex Retail',
  'Nova Health',
  'Horizon Manufacturing'
];

export const AVAILABLE_DEPARTMENTS = [
  'Engineering',
  'Operations',
  'Sales & Marketing',
  'Customer Support',
  'Finance',
  'Human Resources'
];

export const AVAILABLE_WORK_CENTERS = [
  'Headquarters (Main)',
  'North Logistics Center',
  'East Coast Branch',
  'West R&D Lab',
  'South Factory'
];

export const AVAILABLE_PATHOLOGIES = [
  'Musculoskeletal',
  'Mental Health',
  'Respiratory',
  'Cardiovascular',
  'Digestive',
  'Infectious Diseases',
  'Surgery Recovery',
  'Other'
];

export const AVAILABLE_LEAVE_TYPES = [
  'Common Illness',
  'Occupational Accident',
  'Occupational Disease',
  'Non-Occupational Accident'
];
